// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260731232352_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Colegio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoDane")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailContacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colegios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CodigoDane = "113837000123",
                            Direccion = "Turbaco, Bolívar",
                            EmailContacto = "contacto@cuartapozademanga.edu.co",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nit = "800123456-1",
                            Nombre = "Institución Educativa Cuarta Poza de Manga",
                            Telefono = "(605) 6789012"
                        });
                });

            modelBuilder.Entity("Backend.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColegioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColegioId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColegioId = 1,
                            Nombre = "10-A"
                        },
                        new
                        {
                            Id = 2,
                            ColegioId = 1,
                            Nombre = "11-A"
                        },
                        new
                        {
                            Id = 3,
                            ColegioId = 1,
                            Nombre = "11-B"
                        });
                });

            modelBuilder.Entity("Backend.Models.Encuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColegioId")
                        .HasColumnType("int");

                    b.Property<int>("CreadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColegioId");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.ToTable("Encuestas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColegioId = 1,
                            CreadoPorUsuarioId = 2,
                            Descripcion = "Encuesta institucional para evaluar las relaciones interpersonales, seguridad emocional y respeto en el aula.",
                            FechaCreacion = new DateTime(2026, 2, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Diagnóstico de Clima Escolar y Convivencia 2026"
                        });
                });

            modelBuilder.Entity("Backend.Models.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColegioId")
                        .HasColumnType("int");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreAcudiente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentescoAcudiente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoAcudiente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColegioId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Estudiantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColegioId = 1,
                            Curso = "11-A",
                            Eps = "Coosalud",
                            NombreAcudiente = "",
                            ParentescoAcudiente = "",
                            PersonaId = 4,
                            TelefonoAcudiente = "",
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 2,
                            ColegioId = 1,
                            Curso = "10-B",
                            Eps = "Sura",
                            NombreAcudiente = "",
                            ParentescoAcudiente = "",
                            PersonaId = 5,
                            TelefonoAcudiente = "",
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 3,
                            ColegioId = 1,
                            Curso = "9-C",
                            Eps = "Sanitas",
                            NombreAcudiente = "",
                            ParentescoAcudiente = "",
                            PersonaId = 6,
                            TelefonoAcudiente = "",
                            UsuarioId = 6
                        },
                        new
                        {
                            Id = 4,
                            ColegioId = 1,
                            Curso = "8-A",
                            Eps = "Nueva EPS",
                            NombreAcudiente = "",
                            ParentescoAcudiente = "",
                            PersonaId = 7,
                            TelefonoAcudiente = "",
                            UsuarioId = 7
                        });
                });

            modelBuilder.Entity("Backend.Models.Opcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PreguntaId")
                        .HasColumnType("int");

                    b.Property<string>("TextoOpcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.ToTable("Opciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PreguntaId = 1,
                            TextoOpcion = "Excelente"
                        },
                        new
                        {
                            Id = 2,
                            PreguntaId = 1,
                            TextoOpcion = "Bueno"
                        },
                        new
                        {
                            Id = 3,
                            PreguntaId = 1,
                            TextoOpcion = "Regular"
                        },
                        new
                        {
                            Id = 4,
                            PreguntaId = 1,
                            TextoOpcion = "Deficiente"
                        },
                        new
                        {
                            Id = 5,
                            PreguntaId = 2,
                            TextoOpcion = "Nunca"
                        },
                        new
                        {
                            Id = 6,
                            PreguntaId = 2,
                            TextoOpcion = "Rara vez"
                        },
                        new
                        {
                            Id = 7,
                            PreguntaId = 2,
                            TextoOpcion = "Frecuentemente"
                        });
                });

            modelBuilder.Entity("Backend.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("LugarNacimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoIdentificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            Id = 999,
                            Apellido = "Llamas",
                            Direccion = "Sede Central SIAE",
                            Email = "admin@siae.com",
                            LugarNacimiento = "",
                            Nombre = "Gybram (SuperAdmin)",
                            NumeroIdentificacion = "0000000000",
                            Sexo = "Masculino",
                            Telefono = "3000000000",
                            TipoIdentificacion = "CC"
                        },
                        new
                        {
                            Id = 1,
                            Apellido = "Pérez",
                            Direccion = "Turbaco - Centro",
                            Email = "rector@cuartapozademanga.edu.co",
                            LugarNacimiento = "",
                            Nombre = "Pedro",
                            NumeroIdentificacion = "73123456",
                            Sexo = "Masculino",
                            Telefono = "3001112233",
                            TipoIdentificacion = "CC"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Rodríguez",
                            Direccion = "Turbaco - El Carmen",
                            Email = "orientacion@cuartapozademanga.edu.co",
                            LugarNacimiento = "",
                            Nombre = "Sofía",
                            NumeroIdentificacion = "45987654",
                            Sexo = "Femenino",
                            Telefono = "3004445566",
                            TipoIdentificacion = "CC"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Sánchez",
                            Direccion = "Turbaco - La Granja",
                            Email = "coordinacion@cuartapozademanga.edu.co",
                            LugarNacimiento = "",
                            Nombre = "Carlos",
                            NumeroIdentificacion = "92456789",
                            Sexo = "Masculino",
                            Telefono = "3007778899",
                            TipoIdentificacion = "CC"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Llamas",
                            Direccion = "Turbaco - Sector Manga",
                            Email = "gybram@estudiante.edu.co",
                            FechaNacimiento = new DateTime(2009, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LugarNacimiento = "Cartagena",
                            Nombre = "Gybram",
                            NumeroIdentificacion = "1098765432",
                            Sexo = "Masculino",
                            Telefono = "3101234567",
                            TipoIdentificacion = "TI"
                        },
                        new
                        {
                            Id = 5,
                            Apellido = "Gómez Ruiz",
                            Direccion = "Turbaco - Centro",
                            Email = "maria.gomez@estudiante.edu.co",
                            FechaNacimiento = new DateTime(2010, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LugarNacimiento = "Turbaco",
                            Nombre = "María Fernanda",
                            NumeroIdentificacion = "1045678901",
                            Sexo = "Femenino",
                            Telefono = "3129876543",
                            TipoIdentificacion = "TI"
                        },
                        new
                        {
                            Id = 6,
                            Apellido = "Ruiz Martínez",
                            Direccion = "Turbaco - La Granja",
                            Email = "carlos.ruiz@estudiante.edu.co",
                            FechaNacimiento = new DateTime(2011, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LugarNacimiento = "Turbaco",
                            Nombre = "Carlos Andrés",
                            NumeroIdentificacion = "1076543210",
                            Sexo = "Masculino",
                            Telefono = "3154567890",
                            TipoIdentificacion = "TI"
                        },
                        new
                        {
                            Id = 7,
                            Apellido = "Torres Blanco",
                            Direccion = "Turbaco - El Carmen",
                            Email = "valentina.torres@estudiante.edu.co",
                            FechaNacimiento = new DateTime(2012, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LugarNacimiento = "Cartagena",
                            Nombre = "Valentina",
                            NumeroIdentificacion = "1087654321",
                            Sexo = "Femenino",
                            Telefono = "3186543210",
                            TipoIdentificacion = "TI"
                        });
                });

            modelBuilder.Entity("Backend.Models.Pregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EncuestaId")
                        .HasColumnType("int");

                    b.Property<bool>("EsObligatoria")
                        .HasColumnType("bit");

                    b.Property<string>("PrefijoPais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Restriccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextoPregunta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoRespuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EncuestaId");

                    b.ToTable("Preguntas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EncuestaId = 1,
                            EsObligatoria = true,
                            PrefijoPais = "+57",
                            Restriccion = "",
                            TextoPregunta = "¿Cómo evalúas el nivel de respeto y trato entre compañeros en tu salón de clases?",
                            TipoRespuesta = "SeleccionUnica"
                        },
                        new
                        {
                            Id = 2,
                            EncuestaId = 1,
                            EsObligatoria = true,
                            PrefijoPais = "+57",
                            Restriccion = "",
                            TextoPregunta = "¿Has presenciado o experimentado situaciones de acoso o discriminación en la institución?",
                            TipoRespuesta = "SeleccionUnica"
                        },
                        new
                        {
                            Id = 3,
                            EncuestaId = 1,
                            EsObligatoria = true,
                            PrefijoPais = "+57",
                            Restriccion = "",
                            TextoPregunta = "¿Qué propuestas o sugerencias tienes para fortalecer la convivencia pacífica en tu grado?",
                            TipoRespuesta = "TextoAbierto"
                        });
                });

            modelBuilder.Entity("Backend.Models.PreguntaRespuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OpcionSeleccionadaId")
                        .HasColumnType("int");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("int");

                    b.Property<int>("RespuestaEncuestaId")
                        .HasColumnType("int");

                    b.Property<string>("RespuestaTexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OpcionSeleccionadaId");

                    b.HasIndex("PreguntaId");

                    b.HasIndex("RespuestaEncuestaId");

                    b.ToTable("PreguntasRespuestas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OpcionSeleccionadaId = 2,
                            PreguntaId = 1,
                            RespuestaEncuestaId = 1,
                            RespuestaTexto = ""
                        },
                        new
                        {
                            Id = 2,
                            OpcionSeleccionadaId = 5,
                            PreguntaId = 2,
                            RespuestaEncuestaId = 1,
                            RespuestaTexto = ""
                        },
                        new
                        {
                            Id = 3,
                            PreguntaId = 3,
                            RespuestaEncuestaId = 1,
                            RespuestaTexto = "Realizar más talleres grupales de integración y deportes durante los descansos."
                        });
                });

            modelBuilder.Entity("Backend.Models.RegistroCaso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColegioId")
                        .HasColumnType("int");

                    b.Property<int>("CreadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discapacidades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RequiereDUA")
                        .HasColumnType("bit");

                    b.Property<bool>("RequierePIAR")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColegioId");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("RegistrosCasos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColegioId = 1,
                            CreadoPorUsuarioId = 2,
                            Descripcion = "Acompañamiento por adaptación escolar y estrategias socioemocionales de liderazgo positivo en el aula.",
                            Discapacidades = "Ninguna",
                            Estado = "Iniciado",
                            EstudianteId = 1,
                            FechaCreacion = new DateTime(2026, 2, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            RequiereDUA = true,
                            RequierePIAR = false,
                            Tipo = "Convivencia"
                        },
                        new
                        {
                            Id = 2,
                            ColegioId = 1,
                            CreadoPorUsuarioId = 3,
                            Descripcion = "Infracción al manual de convivencia por altercado verbal reiterado durante el descanso.",
                            Discapacidades = "",
                            Estado = "EnProceso",
                            EstudianteId = 2,
                            FechaCreacion = new DateTime(2026, 3, 5, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            RequiereDUA = false,
                            RequierePIAR = false,
                            Tipo = "Disciplinario"
                        },
                        new
                        {
                            Id = 3,
                            ColegioId = 1,
                            CreadoPorUsuarioId = 2,
                            Descripcion = "Atención por dificultad de concentración y ansiedad en evaluaciones. Se aprueba Plan PIAR de adaptación en tiempos de entrega.",
                            Discapacidades = "TDAH, Ansiedad Generalizada",
                            Estado = "EnProceso",
                            EstudianteId = 3,
                            FechaCreacion = new DateTime(2026, 3, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RequiereDUA = true,
                            RequierePIAR = true,
                            Tipo = "Convivencia"
                        },
                        new
                        {
                            Id = 4,
                            ColegioId = 1,
                            CreadoPorUsuarioId = 2,
                            Descripcion = "Aplicación de Primeros Auxilios Psicológicos (PAP) por episodio de hiperventilación previo a examen. Estabilizada exitosamente.",
                            Discapacidades = "Ansiedad Aguda",
                            Estado = "Cerrado",
                            EstudianteId = 4,
                            FechaCreacion = new DateTime(2026, 4, 1, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            RequiereDUA = true,
                            RequierePIAR = false,
                            Tipo = "Convivencia"
                        });
                });

            modelBuilder.Entity("Backend.Models.RespuestaEncuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EncuestaId")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EncuestaId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("RespuestasEncuestas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EncuestaId = 1,
                            EstudianteId = 1,
                            FechaRespuesta = new DateTime(2026, 2, 15, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Backend.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColegioId")
                        .HasColumnType("int");

                    b.Property<string>("Jornada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColegioId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 999,
                            ColegioId = 1,
                            Jornada = "Global",
                            PasswordHash = "superadmin123",
                            PersonaId = 999,
                            Rol = "SUPER_ADMIN",
                            Username = "superadmin"
                        },
                        new
                        {
                            Id = 1,
                            ColegioId = 1,
                            Jornada = "Mañana",
                            PasswordHash = "rector123",
                            PersonaId = 1,
                            Rol = "Rector",
                            Username = "rector"
                        },
                        new
                        {
                            Id = 2,
                            ColegioId = 1,
                            Jornada = "Mañana",
                            PasswordHash = "orientador123",
                            PersonaId = 2,
                            Rol = "Orientador",
                            Username = "orientador"
                        },
                        new
                        {
                            Id = 3,
                            ColegioId = 1,
                            Jornada = "Tarde",
                            PasswordHash = "coordinador123",
                            PersonaId = 3,
                            Rol = "Coordinador",
                            Username = "coordinador"
                        },
                        new
                        {
                            Id = 4,
                            ColegioId = 1,
                            Jornada = "Tarde",
                            PasswordHash = "gybram123",
                            PersonaId = 4,
                            Rol = "Estudiante",
                            Username = "gybram"
                        },
                        new
                        {
                            Id = 5,
                            ColegioId = 1,
                            Jornada = "Mañana",
                            PasswordHash = "1045678901",
                            PersonaId = 5,
                            Rol = "Estudiante",
                            Username = "maria.gomez"
                        },
                        new
                        {
                            Id = 6,
                            ColegioId = 1,
                            Jornada = "Mañana",
                            PasswordHash = "1076543210",
                            PersonaId = 6,
                            Rol = "Estudiante",
                            Username = "carlos.ruiz"
                        },
                        new
                        {
                            Id = 7,
                            ColegioId = 1,
                            Jornada = "Tarde",
                            PasswordHash = "1087654321",
                            PersonaId = 7,
                            Rol = "Estudiante",
                            Username = "valentina.torres"
                        });
                });

            modelBuilder.Entity("Backend.Models.Curso", b =>
                {
                    b.HasOne("Backend.Models.Colegio", "Colegio")
                        .WithMany()
                        .HasForeignKey("ColegioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colegio");
                });

            modelBuilder.Entity("Backend.Models.Encuesta", b =>
                {
                    b.HasOne("Backend.Models.Colegio", "Colegio")
                        .WithMany()
                        .HasForeignKey("ColegioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "CreadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Colegio");

                    b.Navigation("CreadoPorUsuario");
                });

            modelBuilder.Entity("Backend.Models.Estudiante", b =>
                {
                    b.HasOne("Backend.Models.Colegio", "Colegio")
                        .WithMany()
                        .HasForeignKey("ColegioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Colegio");

                    b.Navigation("Persona");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend.Models.Opcion", b =>
                {
                    b.HasOne("Backend.Models.Pregunta", null)
                        .WithMany("Opciones")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Pregunta", b =>
                {
                    b.HasOne("Backend.Models.Encuesta", null)
                        .WithMany("Preguntas")
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.PreguntaRespuesta", b =>
                {
                    b.HasOne("Backend.Models.Opcion", "OpcionSeleccionada")
                        .WithMany()
                        .HasForeignKey("OpcionSeleccionadaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.Pregunta", "Pregunta")
                        .WithMany()
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.RespuestaEncuesta", null)
                        .WithMany("RespuestasDetalle")
                        .HasForeignKey("RespuestaEncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpcionSeleccionada");

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("Backend.Models.RegistroCaso", b =>
                {
                    b.HasOne("Backend.Models.Colegio", "Colegio")
                        .WithMany()
                        .HasForeignKey("ColegioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "CreadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colegio");

                    b.Navigation("CreadoPorUsuario");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("Backend.Models.RespuestaEncuesta", b =>
                {
                    b.HasOne("Backend.Models.Encuesta", "Encuesta")
                        .WithMany()
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encuesta");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("Backend.Models.Usuario", b =>
                {
                    b.HasOne("Backend.Models.Colegio", "Colegio")
                        .WithMany()
                        .HasForeignKey("ColegioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colegio");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Backend.Models.Encuesta", b =>
                {
                    b.Navigation("Preguntas");
                });

            modelBuilder.Entity("Backend.Models.Pregunta", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("Backend.Models.RespuestaEncuesta", b =>
                {
                    b.Navigation("RespuestasDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
